# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 330bfcde61a7f4a73d6bc154acdc78b2939a086f61a95ee473b56ae64cab7661c3c306e84bde0449d84532961abbef7dd9705b63256713acf1be066670161b61

test:
  secret_key_base: d032266b9af0c403e0bdec35fe71262c0b4a4f09e41893b717304e669d89667878bd77034708905a814754c14017419211b9a52f830e3363925cb08d15c622fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
